(()=>{const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let S={lang:localStorage.bt_lang||"zh",p:localStorage.bt_p||"gentle",w:+localStorage.bt_w||75,l:+localStorage.bt_l||55,msg:JSON.parse(localStorage.bt_msg||"[]")};
const T={zh:{profile:"我的资料",style:"聊天风格",gentle:"温柔倾听型",friend:"好朋友型",rational:"理性陪伴型",cheer:"鼓励成长型",study:"学习搭子型",gd:"安静地听你说",fd:"像朋友一样聊天",rd:"一起整理思路",cd:"给你一点动力",sd:"一起学习和规划",custom:"自定义",warm:"温暖程度",length:"回复长度",online:"在线 · 随时可以聊聊",clear:"清空",topic:"从一个话题开始",local:"聊天记录只保存在这个浏览器中。",rules:"使用规则",name:"名字",language:"语言",save:"保存",ruleTitle:"使用规则",r1:"不要分享密码、家庭住址、银行卡等私人信息。",r2:"BloomTalk 是一个本地聊天原型，不是专业心理咨询服务。",r3:"如果你遇到现实中的紧急危险，请联系可信任的成年人或当地紧急服务。",welcome:"嗨！我是 Bloom。你可以把今天发生的事情告诉我，我们慢慢聊。",topics:["今天过得怎么样？","我最近有点烦","陪我聊聊天","我需要学习建议"]},en:{profile:"My profile",style:"Chat style",gentle:"Gentle Listener",friend:"Best-Friend Vibe",rational:"Calm & Rational",cheer:"Cheerleader",study:"Study Buddy",gd:"Quietly listens to you",fd:"Talk like old friends",rd:"Sort your thoughts",cd:"A little motivation",sd:"Learn & plan together",custom:"Customize",warm:"Warmth",length:"Reply length",online:"Online · Always here to chat",clear:"Clear",topic:"Start with a topic",local:"Your conversations stay in this browser.",rules:"Guidelines",name:"Name",language:"Language",save:"Save",ruleTitle:"Guidelines",r1:"Don't share passwords, your home address, bank information, or other private information.",r2:"BloomTalk is a local chat prototype, not professional counseling.",r3:"If you are in immediate real-world danger, contact a trusted adult or local emergency services.",welcome:"Hi! I'm Bloom. Tell me what's on your mind, and we can take it one step at a time.",topics:["How was your day?","I'm a little stressed","Talk with me","I need study advice"]}};
const R={zh:{gentle:["我在听。你可以慢慢说，不需要一次把所有事情都讲清楚。","听起来这件事让你有些难受。我们可以一点一点聊。","学习压力有时候真的会让人很累。我们可以把事情拆成几个小步骤。","听起来是件让你开心的事情！这种小小的快乐也值得好好记住。","朋友之间的事情有时候很复杂。你可以告诉我发生了什么，我会认真听。"],friend:["当然！来，跟我说说发生了什么，我陪你聊。","啊……听起来真的挺难受的。我们慢慢说。","懂你！学校的事情一多真的会很烦。我们一起想个简单的办法。","哇，那听起来不错！快跟我讲讲，我想听更多～","朋友之间的事情真的很容易让人纠结。你先把事情告诉我。"],rational:["我们可以先明确问题，再看看有哪些选择。你最在意的部分是什么？","我们可以把它分成：发生了什么、你的感受、接下来能做什么。","先确定最紧急的一件事，然后再安排其他任务。","很好。想想是什么因素让这次经历变得顺利。","可以先区分事实和猜测，再考虑你希望这段关系变成什么样。"],cheer:["你已经愿意说出来了，这本身就是一个很好的开始！","你现在的感受是可以被理解的。一步一步来就好。","不用一次完成全部任务！先完成最小的一步。","太好了！好好享受这个开心的瞬间。","你愿意认真面对朋友之间的问题已经很勇敢了。"],study:["学习搭子上线！告诉我你正在学什么，我可以帮你拆成小任务。","先别给自己太大压力。我们可以从一个最简单的学习任务开始。","把作业按“最急、最难、最快完成”分类，然后先处理其中一项。","很好！趁状态不错，可以顺手完成一个小任务。","如果朋友的问题影响了学习，我们可以先处理情绪，再安排学习时间。"]},en:{gentle:["I'm listening. You can take your time—you don't have to explain everything at once.","That sounds difficult. We can take it one step at a time.","School pressure can feel exhausting. We can break it into smaller steps.","That sounds like something worth being happy about!","Friendships can be complicated. Tell me what happened, and I'll listen."],friend:["Of course! Tell me what happened. I'm happy to chat with you.","Aw, that sounds really hard. Take a breath and tell me when you're ready.","I get it! School can become a lot. Let's find a simple way to handle it.","That sounds great! Tell me more—I want to hear about it.","Friend stuff can get confusing. Tell me what happened first."],rational:["Let's define the problem first, then look at your options.","We can separate it into what happened, how you feel, and what you can do next.","Start with the most urgent task, then organize the rest.","That's great. Think about what helped it go well.","It can help to separate facts from guesses, then think about what you want."],cheer:["Talking about it is already a good first step. Let's keep moving forward.","Your feelings make sense. You can work through things one step at a time.","You don't have to finish everything at once! Start with the smallest step.","That's awesome! Enjoy the good moment.","It's brave to take friendship problems seriously. One step at a time."],study:["Study buddy mode is on! Tell me what you're studying, and we can make smaller tasks.","Don't put too much pressure on yourself. Start with one simple task.","Sort your work by urgency and difficulty, then start with one item.","Nice! Finish one small task and keep the momentum going.","If friendship stress affects school, we can deal with the feelings first and then plan study time."]}};
function save(){localStorage.bt_lang=S.lang;localStorage.bt_p=S.p;localStorage.bt_w=S.w;localStorage.bt_l=S.l;localStorage.bt_msg=JSON.stringify(S.msg)}
function esc(x){return String(x).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
function render(){let b=$("#messages");b.innerHTML=S.msg.map(m=>`<div class="row ${m.u?"mine":""}"><div class="bubble ${m.u?"":"bub"}">${esc(m.t)}<div class="tm">${new Date(m.d).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}</div></div></div>`).join("");b.scrollTop=b.scrollHeight}
function translate(){let t=T[S.lang];$$("[data-i]").forEach(e=>e.textContent=t[e.dataset.i]||e.textContent);$$(".topics button").forEach((e,i)=>e.textContent=t.topics[i]);$("#input").placeholder=S.lang==="zh"?"输入你想说的话……":"Type something…";$("#lang").textContent=S.lang==="zh"?"EN":"中";$("#wv").textContent=S.w+"%";$("#lv").textContent=S.l+"%";render()}
function classify(x){x=x.toLowerCase();if(S.lang==="zh")return /难过|伤心|压力|焦虑|烦|累|不开心|孤独/.test(x)?1:/学校|作业|考试|学习|数学|英语|生物|老师/.test(x)?2:/开心|高兴|快乐|成功|喜欢|棒/.test(x)?3:/朋友|同学|关系|聊天/.test(x)?4:0;return /sad|upset|stress|anxious|tired|lonely|hurt/.test(x)?1:/school|homework|exam|study|math|english|biology|teacher/.test(x)?2:/happy|excited|great|awesome|proud/.test(x)?3:/friend|classmate|relationship|talk/.test(x)?4:0}
function send(v){v=v.trim();if(!v)return;S.msg.push({u:1,t:v,d:Date.now()});save();render();let r=R[S.lang][S.p][classify(v)];if(S.l<35)r=r.split(/[。.!！?？]/)[0]+(S.lang==="zh"?"。":".");if(S.l>80)r+=(S.lang==="zh"?" 如果你愿意，可以继续告诉我更多，我会跟着你的节奏聊。":" If you'd like, you can tell me more, and I'll follow your pace.");setTimeout(()=>{S.msg.push({u:0,t:r,d:Date.now()});save();render()},350)}
function modal(x,on){$(x).classList.toggle("open",on)}
function toast(x){let t=$("#toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1500)}
function init(){if(!S.msg.length)S.msg=[{u:0,t:T[S.lang].welcome,d:Date.now()}];$("#warmth").value=S.w;$("#length").value=S.l;translate();
$$(".person").forEach(x=>x.onclick=()=>{$$(".person").forEach(y=>y.classList.remove("active"));x.classList.add("active");S.p=x.dataset.p;save()});
$("#warmth").oninput=e=>{S.w=+e.target.value;translate();save()};$("#length").oninput=e=>{S.l=+e.target.value;translate();save()};
$("#lang").onclick=()=>{S.lang=S.lang==="zh"?"en":"zh";save();translate()};$("#theme").onclick=()=>document.body.classList.toggle("dark");
$("#clear").onclick=()=>{S.msg=[];save();render();toast(T[S.lang].clear)};$("#form").onsubmit=e=>{e.preventDefault();send($("#input").value);$("#input").value=""};$("#input").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#form").requestSubmit()}};
$$(".topics button").forEach(b=>b.onclick=()=>{$("#input").value=b.textContent;$("#input").focus()});
$("#profile").onclick=()=>modal("#profileModal",1);$("#rules").onclick=()=>modal("#rulesModal",1);$$(".x").forEach(b=>b.onclick=()=>$$(".modal").forEach(m=>modal("#"+m.id,0)));$$(".modal").forEach(m=>m.onclick=e=>{if(e.target===m)modal("#"+m.id,0)});
$("#save").onclick=()=>{localStorage.bt_name=$("#name").value;S.lang=$("#language").value;save();translate();modal("#profileModal",0);toast(T[S.lang].save)}}
document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init()})();